name: newmanbarber
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.2.0
  # Firebase Authentication
  firebase_auth: ^5.1.2
  # Firestore Database
  cloud_firestore: ^5.1.0
  # Firebase Storage
  firebase_storage: ^12.1.0
  # Image Picker
  image_picker: ^1.1.2
  # Cache de Imagens
  cached_network_image: ^3.3.1
  # Formatação de Datas (Atualizado para ser compatível com flutter_localizations)
  intl: any

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
