name: newmanbarber
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.2.0
  # Firebase Authentication
  firebase_auth: ^5.1.2
  # Firestore Database
  cloud_firestore: ^5.1.0
  # Firebase Storage (Para imagens)
  firebase_storage: ^12.1.0
  # Image Picker (Para Camera/Galeria)
  image_picker: ^1.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
